services:
  - type: web
    name: alpha-x-calls-bot
    runtime: python
    plan: free
    rootDir: bot
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: VIP_GROUP_LINK
        sync: false
      - key: SUPPORT_USERNAME
        value: "Dave_211"
      - key: CHANNEL_NAME
        value: "Alpha_X_Calls"
      - key: DEX_CHAINS
        value: "solana,ethereum,bsc,base"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PORT
        value: "10000"
      - key: SCAN_INTERVAL
        value: "180"
      - key: SEND_INTERVAL_MIN
        value: "120"
      - key: SEND_INTERVAL_MAX
        value: "180"
      - key: MIN_MC
        value: "10000"
      - key: MAX_MC
        value: "800000"
